### ISSUE TITLE
Missing "online form" link

### ISSUE THREAD

**Issue by ctron** [commonhaus/commonhaus.github.io#21]
In the about page, under contact us (https://www.commonhaus.org/community/#contact-us), it says:

> please contact us through our online form

But there seems to be no link to such an online form.

**Comment by ebullient** [comment]
yep. Working on it. `hello@commonhaus.org` work, as does opening a discussion here: 

https://github.com/commonhaus/foundation/discussions

I want to wrap our addresses to make it easier to send a note to the right place. Ran out of time to do all of the things ahead of last week.

Thanks for opening an issue. =)

**Comment by ebullient** [comment]
Fixed in the [foundation repository](https://github.com/commonhaus/foundation/commit/b8e9dbc2a154548c566ecacb5a38273ea0150a65).

Thanks again for noticing. =)
